name: Deploy to Timeweb

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend
        run: |
          docker build -t danks25/backend:latest -f backend/Dockerfile ./backend
          docker push danks25/backend:latest

      - name: Build and push frontend
        run: |
          docker build -t danks25/frontend:latest -f frontend/Dockerfile ./frontend
          docker push danks25/frontend:latest

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key
          chmod 600 private_key

      - name: Restart containers on server
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST <<'EOF'
            cd /home/root
            docker-compose pull
            docker-compose down
            docker-compose up -d
            EOF
