name: Deploy to Timeweb

on:
  push:
    branches:
      - main  # Запускать при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Войти в Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Собрать и запушить backend
        run: |
          docker build -t danks25/backend:latest -f backend/Dockerfile ./backend
          docker push danks25/backend:latest

      - name: Собрать и запушить frontend
        run: |
          docker build -t danks25/frontend:latest -f frontend/Dockerfile ./frontend
          docker push danks25/frontend:latest

      - name: Установить SSH-ключ
        run: |
          echo "$SSH_KEY" > private_key && chmod 600 private_key

      - name: Перезапустить контейнеры на сервере
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            cd /home/root
            docker-compose pull
            docker-compose down
            docker-compose up -d
          EOF

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
